### ISSUE TITLE
[Crash] ...

### ISSUE THREAD

**Issue by Cristo-Ari** [SuperMartijn642/WirelessChargers#31]
**Version Info**
- Minecraft, ...
- Wireless Chargers, ...

**Steps to Reproduce**
scroll through the list of items from mods

**Crash report (~/logs/latest.log)**
...
[12:39:31] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering Block Entity
	at knot/net.minecraft.class_757.method_3192(class_757.java:922) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1285) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:102) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1087.method_4707(net.minecraft.class_2680, net.minecraft.class_2350, net.minecraft.class_5819)" because "bakedModel" is null
	at knot/net.minecraft.class_778.handler$jpb000$sodium$renderFast(class_778.java:3077) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_778.method_3367(class_778.java) ~[client-intermediary.jar:?]
	at knot/com.supermartijn642.wirelesschargers.ChargerRenderer.render(ChargerRenderer.java:29) ~[wirelesschargers-1.0.9-fabric-mc1.21.jar:?]
	at knot/com.supermartijn642.wirelesschargers.ChargerRenderer.render(ChargerRenderer.java:18) ~[wirelesschargers-1.0.9-fabric-mc1.21.jar:?]
	at knot/net.minecraft.class_824.method_23080(class_824.java:98) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_824.method_3554(class_824.java:104) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_824.method_23077(class_824.java:98) ~[client-intermediary.jar:?]
	at knot/com.supermartijn642.core.render.BlockEntityCustomItemRenderer.render(BlockEntityCustomItemRenderer.java:49) ~[supermartijn642corelib-1.1.17c-fabric-mc1.21.jar:?]
	at knot/net.minecraft.class_756.handler$dnf000$fabric-rendering-v1$fabric_onRender(class_756.java:1041) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_756.method_3166(class_756.java) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_918.method_23179(class_918.java:127) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_332.method_51425(class_332.java:582) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_332.method_51424(class_332.java:564) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_332.method_51427(class_332.java:540) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_481.method_2468(class_481.java:915) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_481.method_2389(class_481.java:848) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_465.method_25420(class_465.java:172) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_437.method_25394(class_437.java:126) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_465.method_25394(class_465.java:100) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_485.method_25394(class_485.java:32) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_481.method_25394(class_481.java:778) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_437.method_47413(class_437.java:117) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.mixinextras$bridge$method_47413$311(class_757.java) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.wrapOperation$dpl000$fabric-screen-api-v1$onRenderScreen(class_757.java:5586) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.mixinextras$bridge$wrapOperation$dpl000$fabric-screen-api-v1$onRenderScreen$317(class_757.java) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.wrapOperation$fjc000$konkrete$wrapRenderScreen_Konkrete(class_757.java:10622) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.method_3192(class_757.java:913) ~[client-intermediary.jar:?]
	... 9 more

**Comment by Cristo-Ari** [comment]
1.21.1 mod version 1.0.9

**Comment by SuperMartijn642** [comment]
This has already been fixed 1.0.9a, however it seems the file was only marked 1.21. I have now marked the file for 1.21.1 as well.
